CM_E(CM_ERR_NOUSR, 	"User does not exist")
CM_E(CM_ERR_NOGRP, 	"Group does not exist")
CM_E(CM_ERR_NOTFILE,	"Not a file")
CM_E(CM_ERR_NOTDIR,	"Not a directory")
CM_E(CM_ERR_NOTLINK,	"Not a link")
CM_E(CM_ERR_NOTRGT,	"No target specified")
CM_E(CM_ERR_GIDEXISTS,	"GID already in use")
